### ISSUE TITLE
Error parsing .gtf

### ISSUE THREAD

**Issue by SimonHegele** [ConesaLab/SQANTI-SIM#7]
Hello,

I tried using sqanti-sim.py classif with the .gtf-file for the GCF_000002985.6 c. elegans assembly (https://www.ncbi.nlm.nih.gov/datasets/genome/GCF_000002985.6/). Is this a problem of SQANTI-SIM or of the file I used? If it is the file, could you provide one that works for SQANTI-SIM?

Thanks!

Error: exonFrames field is being added, but I found a gene (NM_078464.8) with CDS but no valid frames.  This can happen if program is invoked with -genePredExt but no valid frames are given in the file.  If the 8th field of GFF/GTF file is always a placeholder, then don't use -genePredExt.
30536 errors
Traceback (most recent call last):
  File "/root/SQANTI-SIM/sqanti-sim.py", line 539, in <module>
    res = classif(input)
          ^^^^^^^^^^^^^^
  File "/root/SQANTI-SIM/sqanti-sim.py", line 64, in classif
    trans_info = classify_gtf.classify_gtf(args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/SQANTI-SIM/src/classify_gtf.py", line 1313, in classify_gtf
    trans_by_chr = gtf_parser(args.gtf)
                   ^^^^^^^^^^^^^^^^^^^^
  File "/root/SQANTI-SIM/src/classify_gtf.py", line 194, in gtf_parser
    if subprocess.check_call(cmd, shell=True) != 0:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/SQANTI-SIM.env/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/root/SQANTI-SIM/src/SQANTI3/utilities/gtfToGenePred ../elegans/ncbi_dataset/GCF_000002985.6/genomic.gtf ../elegans/ncbi_dataset/GCF_000002985.6/genomic.genePred -genePredExt -allErrors -ignoreGroupsWithoutExons' returned non-zero exit status 255.

**Comment by SimonHegele** [comment]
The .gtf-file GCF_037355615.1 drosophila genome assembly was processed perfectly fine. The first annotation I used apparently didn't include the ORFs. Sorry to have bothered you.
